version: "3.8"

services:
    mongodb:
        image: mongo:5.0
        restart: always
        environment:
            MONGO_INITDB_DATABASE: gf-kanban
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
            - ./init.js:/docker-entrypoint-initdb.d/init.js

    mongo-express:
        image: mongo-express:0.54
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - "8081:8081"

volumes:
    mongodb_data:
        driver: local